[package]
name = "onebrc"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = "thin"

[dependencies]
hashbrown = "0.14.5"
memmap = "0.7.0"
ahash = "0.8.11"
windows-sys = { version = "0.52.0", features = ["Win32_Storage_FileSystem"] }
